install:
	npm ci

start:
	npm start

build:
	npm build

lint:
	npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml .

run:
	make start & npx start-server

a:
	npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml src/components/ChatPage.jsx
